GET http://localhost:8080/produto

###
GET http://localhost:8080/produto/4

###
DELETE  http://localhost:8080/produto/2

###
POST http://localhost:8080/produto
Content-Type: application/json

{
    "nome": "ps4 2018",
    "descricao": "HD 1tb",
    "preco": 2500
}

###

PATCH http://localhost:8080/produto/3
Content-Type: application/json

{
    "preco": 3899
}